spring:
  application:
    name: Home Surf
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/home-surf?currentSchema=main
    username: postgres
    password: pass123
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #hbm2ddl:
        #  auto: create
