server:
  port: 8443
  servlet:
    context-path: /home-surf
  ssl:
    enabled: true
    key-store: ./src/main/resources/homesurf.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: homesurf
spring:
  profiles:
    active: default
  application:
    name: Home Surf
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/home-surf?currentSchema=main
    username: postgres
    password: pass123
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #hbm2ddl:
        #  auto: create
